## Numpy

In [34]:
import numpy as np

In [35]:
l=[12,34,32,12,35,56]
print(type(l))

<class 'list'>


In [36]:
l=[12,34,32,12,35,56]
x=np.array(l)
x

array([12, 34, 32, 12, 35, 56])

In [37]:
type(x)

numpy.ndarray

In [6]:
l=[12,34,32,12,35,56]
x=len(l)
print(x)

6


In [40]:
l=[12,34,32,12,35,56]
x=np.array(l).reshape(2,3)
x

array([[12, 34, 32],
       [12, 35, 56]])

In [41]:
type(x)

numpy.ndarray

In [10]:
l=[12,34,32,12,35,56]
x=[]
for i in l:
    j=i+10
    x.append(j)
print(x)
    

[22, 44, 42, 22, 45, 66]


In [12]:
l=[12,34,32,12,35,56]
x=np.array(l)
y=x+10
print(y)

[22 44 42 22 45 66]


In [13]:
l=[12,34,32,12,35,56]
x=l*2
print(x)

[12, 34, 32, 12, 35, 56, 12, 34, 32, 12, 35, 56]


In [14]:
l=[12,34,32,12,35,56]
x=np.array(l)
y=x*2
print(y)

[ 24  68  64  24  70 112]


In [43]:
l=[12,13,14,15,16,17,22,33,42,54,87,65]
x=np.array(l)
y=x[1:7]
y

array([13, 14, 15, 16, 17, 22])

In [46]:
l=[12,13,14,15,16,17,22,33,42,54,87,65]
x=np.array(l).reshape(3,4)
y=x[1,1]
y


17

In [48]:
l=[12,13,14,15,16,17,22,33,42,54,87,65]
x=np.array(l).reshape(3,4)
y=x[1:3,1:3]
y

array([[17, 22],
       [54, 87]])

In [49]:
# Identity metrix
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# zeroes array
x=np.zeros(9).reshape(3,3)
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# Ones array
x=np.ones(9).reshape(3,3)
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
x=(np.ones(9)*2).reshape(3,3)
x

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [58]:
x=np.random.rand(9).reshape(3,3)
x

array([[0.58696938, 0.62036753, 0.02643411],
       [0.42818987, 0.30438205, 0.31671303],
       [0.69957797, 0.98717451, 0.51115537]])

In [60]:
x=np.random.randint(10)
x

9

In [61]:
x=np.random.randint(10,20)
x

14

In [68]:
x=np.random.randint(10,20,6)
x

array([19, 15, 15, 13, 12, 16])

In [70]:
x=np.random.randn(10)
x

array([-0.31541174, -1.29226557, -0.15320888,  1.65061761, -0.56436483,
       -0.25574155, -0.70841913, -2.63840083, -0.25981261,  1.17955911])

In [85]:
l=["vivek","shirish","arvind","kalyani","harshvardhan"]
x=np.random.choice(l)
print(x)

shirish


In [86]:
x=np.random.randint(1,10,9)
x

array([6, 9, 6, 9, 5, 6, 5, 9, 1])

In [87]:
np.sin(x)

array([-0.2794155 ,  0.41211849, -0.2794155 ,  0.41211849, -0.95892427,
       -0.2794155 , -0.95892427,  0.41211849,  0.84147098])

In [88]:
np.cos(x)

array([ 0.96017029, -0.91113026,  0.96017029, -0.91113026,  0.28366219,
        0.96017029,  0.28366219, -0.91113026,  0.54030231])

In [89]:
np.tan(x)

array([-0.29100619, -0.45231566, -0.29100619, -0.45231566, -3.38051501,
       -0.29100619, -3.38051501, -0.45231566,  1.55740772])

In [94]:
np.log(x)

array([1.79175947, 2.19722458, 1.79175947, 2.19722458, 1.60943791,
       1.79175947, 1.60943791, 2.19722458, 0.        ])

In [95]:
1/np.log(x)

<ipython-input-95-76005824028e>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/np.log(x)


array([0.55811063, 0.45511961, 0.55811063, 0.45511961, 0.62133493,
       0.55811063, 0.62133493, 0.45511961,        inf])

In [96]:
np.log10(x)

array([0.77815125, 0.95424251, 0.77815125, 0.95424251, 0.69897   ,
       0.77815125, 0.69897   , 0.95424251, 0.        ])

In [97]:
np.exp(x)

array([4.03428793e+02, 8.10308393e+03, 4.03428793e+02, 8.10308393e+03,
       1.48413159e+02, 4.03428793e+02, 1.48413159e+02, 8.10308393e+03,
       2.71828183e+00])

In [98]:
x=np.random.randn(9)
x

array([ 0.33415113,  0.38350402,  0.69569247,  0.73558598,  0.71271341,
        1.51135975, -0.33030187, -0.2017614 ,  0.66576823])

In [100]:
z=np.abs(x)
z

array([0.33415113, 0.38350402, 0.69569247, 0.73558598, 0.71271341,
       1.51135975, 0.33030187, 0.2017614 , 0.66576823])

In [101]:
np.round(z,decimals=2)

array([0.33, 0.38, 0.7 , 0.74, 0.71, 1.51, 0.33, 0.2 , 0.67])